runtime: nodejs18
service: backend

env_variables:
  PORT: "5000"
  DB_HOST: ${secrets.my-db-host}
  DB_NAME: ${secrets.my-db-name}
  DB_USERNAME: ${secrets.my-db-username}
  DB_PASSWORD: ${secrets.my-db-password}

handlers:
  - url: /.*
    script: auto
